venv = /home/rwalk/Projects/python3/venv/lib64/python3.8/site-packages/
bin = /home/rwalk/bin/watiba-c
install: watiba.py
	cp watiba.py $(venv)/.
	cp watiba.py /usr/local/lib/python3.8/dist-packages/.
	cp ../bin/watiba-c.py $(bin)
	chmod +x $(bin)
